server:
  port: 8082
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true  #开启feign和sentinel的整合
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商场购物车接口文档"
    package: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8091 #控制台地址
      http-method-specify: true  # http方法详情
      datasource:
        ds1:  #配置文件的数据源名称
          nacos:
            server-addr: 192.168.1.123:8848
            data-id: degrade.json
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: degrade