spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  # datasource
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.mh.springbootmybatis.domain
